<?php
// Property of: Parallax Digital Studios, Inc.
// htmltemplates/footer.php
// Updated: 09.03.2011_rg, 09.04.2011_rg, 04.12.2012_rg

if(preg_match('#' . basename(__FILE__) . '#', $_SERVER['PHP_SELF'])) { exit(0); } // This template must be included in a calling routine

?>

						<!------------------new footer----------------------------->						<div class="footlog"">	<div class="ljplogo"><a href ="http://www.lightjetsplus.com/"><img src="/images/LightJetsPlus_Logo.png" style=" padding-right: 40px; padding-top:-20px;"/></a></div>	<div class="bblg">	<a href ="http://www.bigpostersplus.com/"><img src="/images/BigPostersLogo.png" style="padding-right: 40px;" /></a></div>	<div class="prlg"> <a href ="http://www.parallaxdigital.com/"><img src="/images/parallaxlogo.jpg" /></a></div>	</div>			<div style="position:relative;width:944px;height:88px;">					 <!--	<?php if (!$local_ommitfooterbuttons) { ?><div style="position:absolute;top:2px;left:480px;width:157px;height:33px;">-->																		<!--<a title="Send me a Sample" href="javascript:sendsample();"><img src="/images/button-sendsample.jpg" alt="" width="157" height="33" border="0" /></a>--></div>					<div style="position:absolute;top:9px;left:-40px;width:249px;height:20px;">					<!--	<div align="right"><span class="footer_news">Sign up for News &amp; Offers</span></div>-->					</div>					<div style="position:absolute;top:2px;left:650px;width:207px;height:33px;">												<!--<a title="Email this page to a friend" href="javascript:email2friend();"><img src="/images/button-emailpage.jpg" alt="" width="207" height="33" border="0" /></a>--></div>					<!--<?php include('icontactform.php'); ?><?php } ?>-->										<div style="position:absolute;top:145px;left:240px;width:700px;height:16px;">						<div style="margin-left: 80px">							<span class="footer_type"><a title="About" href="/about">About</a></span><span class="footer_type_pipe"> | </span><span class="footer_type"><a title="FAQ" href="/faq">FAQ</a></span><span class="footer_type_pipe"> | </span><span class="footer_type"><a title="Contact" href="/contact">Contact</a></span><span class="footer_type_pipe"> | </span><span class="footer_type"><a title="Privacy" href="/privacy">Privacy</a></span><span class="footer_type_pipe"> | </span><span class="footer_type"><a title="Terms of Service" href="/termsofservice">Terms of Service</a></span><span class="footer_type_pipe"> | </span><span class="footer_type"><a title="Site Map" href="/sitemap">Site Map</a></span><span class="footer_type_pipe"> | </span><span class="footer_type">Site by <a class="copyright" title="Novatross- IQ" href="http://www.novatross.com" target="_blank">Novatross - IQ</a></span>							<!--<?php if (getAuthenticationFlag()) { ?><br /><span id="toolbox"></span><?php } ?><?php echo($local_footerquotebuttons); ?>-->						</div>					</div>					<div style="position:absolute;top:171px;left:330px;width:393px;height:16px;">						<div align="right">							<span class="copyright"><a title="Contact" href="/">Copyright &copy; BigPostersPlus.com</a></span></div>					</div>				</div>												<!------------ end footer------------------------------->	
																			<?php if (getAuthenticationFlag()) { ?>
								<br /><span id="toolbox"></span>
								<?php if ($pageid == 'home') { ?>
									<div class="type_basic" style="width:300px; border-width: 1px; border-color:#D94731; border-style:dashed; margin-top:10px; margin-bottom:20px;" id="<?php echo(fn_makeid('headline')); ?>"><?php echo(lclCUSTOM_fetchC('headline')); ?></div>
								<?php } ?>					
							<?php } ?>
